other = "Clarify Documentation and Type Hints of `Input(Paid)Media`"
documentation = "Clarify Documentation and Type Hints of `Input(Paid)Media`"
[[pull_requests]]
uid = "4762"
author_uid = "Bibo-Joshi"
closes_threads = []
