dependencies = "Bump astral-sh/setup-uv from 5.4.1 to 6.3.1"
internal = "Bump astral-sh/setup-uv from 5.4.1 to 6.3.1"
[[pull_requests]]
uid = "4842"
author_uid = "dependabot[bot]"
closes_threads = []
