highlights = "Full Support for Bot API 9.1"

features = """
New filters based on Bot API 9.1:

* ``filters.StatusUpdate.DIRECT_MESSAGE_PRICE_CHANGED`` for ``Message.direct_message_price_changed``
"""

pull_requests = [
  { uid = "4847", author_uid = "Bibo-Joshi", closes_threads = ["4845"] },
  { uid = "4849", author_uid = "harshil21" },
  { uid = "4851", author_uid = "harshil21" },
]
