internal = "Add a ``uv.lock`` lockfile for reproducible environments when installing ``python-telegram-bot`` with ``uv``."
[[pull_requests]]
uid = "4890"
author_uid = "harshil21"
closes_threads = ["4796"]
