features = """
Full Support for Bot API 10.0

.. warning::

    - Bot API 10.0 introduces a now required argument ``members_only`` to ``Poll``. For backward compatibility, the argument is currently still marked as optional in the signature and its presence is enforced through a runtime check. In future versions, this argument will be made required in the signature as well.

    Please make sure to update your code accordingly to avoid potential issues in the future. We recommend using keyword arguments to ensure compatibility with future updates.
"""

pull_requests = [
  { uid = "5229", author_uid = "aelkheir", closes_threads = ["5228"] },
  { uid = "5230", author_uid = "harshil21" },
  { uid = "5235", author_uid = "harshil21" },
  { uid = "5238", author_uid = "harshil21" },
  { uid = "5232", author_uid = "aelkheir" },
]
