# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements-docs.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3"  # latest stable cpython version
  jobs:
    post_build:
      # Based on https://github.com/readthedocs/readthedocs.org/issues/3242#issuecomment-1410321534
      # This provides a HTML zip file for download, with the same structure as the hosted website
      - mkdir --parents $READTHEDOCS_OUTPUT/htmlzip
      - cp --recursive $READTHEDOCS_OUTPUT/html $READTHEDOCS_OUTPUT/$READTHEDOCS_PROJECT
      # Hide the "other versions" dropdown. This is a workaround for those versions being shown,
      # but not being accessible, as they are not built. Also, they hide the actual sidebar menu
      # that is relevant only on ReadTheDocs.
      - echo "#furo-readthedocs-versions{display:none}" >> $READTHEDOCS_OUTPUT/$READTHEDOCS_PROJECT/_static/styles/furo-extensions.css
      - cd $READTHEDOCS_OUTPUT ; zip --recurse-path --symlinks htmlzip/$READTHEDOCS_PROJECT.zip $READTHEDOCS_PROJECT

search:
  ranking: # bump up rank of commonly searched pages: (default: 0, values range from -10 to 10)
    telegram.bot.html: 7
    telegram.message.html: 3
    telegram.update.html: 3
    telegram.user.html: 2
    telegram.chat.html: 2
    telegram.ext.application.html: 3
    telegram.ext.filters.html: 3
    telegram.ext.callbackcontext.html: 2
    telegram.ext.inlinekeyboardbutton.html: 1

    telegram.passport*.html: -7

  ignore:
    - changelog.html
    - coc.html
    - bot_methods.html#
    - bot_methods.html
    # Defaults
    - search.html
    - search/index.html
    - 404.html
    - 404/index.html'
