#
#  A library that provides a Python interface to the Telegram Bot API
#  Copyright (C) 2015-2026
#  Leandro Toledo de Souza <devs@python-telegram-bot.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Lesser Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser Public License for more details.
#
#  You should have received a copy of the GNU Lesser Public License
#  along with this program.  If not, see [http://www.gnu.org/licenses/].
"""Generate PTB's API reference from its public exports.

Sphinx discovers documents from physical source files before it reads their toctrees. Autosummary
can create those files, but normally needs a maintained RST list of objects. This extension instead
collects objects from PTB's ``__all__`` exports during ``builder-inited`` and writes the required
sources before discovery. During ``source-read``, it adds the current navigation in memory, so RST
files never contain generated class lists.

Maintained sources live in module-shaped directories for readability. Small generated wrappers
preserve the historic dotted document names and URLs. Generated files remain on disk, and are only
rewritten when their content changes, so Sphinx's normal mtime cache remains effective.

Relevant Sphinx documentation:

* Autosummary: https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html
* Build events: https://www.sphinx-doc.org/en/master/extdev/event_callbacks.html
"""

import tempfile
from collections.abc import Mapping, Sequence
from pathlib import Path
from types import ModuleType
from typing import Final, NamedTuple

from sphinx.application import Sphinx
from sphinx.errors import ExtensionError
from sphinx.ext.autosummary.generate import generate_autosummary_docs
from sphinx.util.typing import ExtensionMetadata

import telegram
import telegram.ext
import telegram.request


class ApiCategory(NamedTuple):
    """Describe one topic page and the internal modules whose objects belong on it."""

    title: str
    module_prefixes: tuple[str, ...]


class MaintainedFragment(NamedTuple):
    """Connect a nested maintained source to its generated dotted-name wrapper."""

    wrapper_path: Path
    relative_path: Path


GENERATED_MARKER: Final[str] = ".. Autogenerated page: True"
MAINTAINED_MARKER: Final[str] = ".. Autogenerated page: False"
FRAGMENT_DIRECTORIES: Final[tuple[str, ...]] = ("examples", "telegram", "telegram_auxil")
API_MODULES: Final[tuple[ModuleType, ...]] = (telegram, telegram.ext, telegram.request)

# The key is the Sphinx document name. The value supplies its title and the internal module
# prefixes used to recognize its public objects; new objects in those modules need no docs edit.
API_CATEGORIES: Final[dict[str, ApiCategory]] = {
    "telegram.stickers-tree": ApiCategory(
        title="Stickers",
        module_prefixes=("telegram._files.inputsticker", "telegram._files.sticker"),
    ),
    "telegram.inline-tree": ApiCategory(
        title="Inline Mode",
        module_prefixes=(
            "telegram._choseninlineresult",
            "telegram._inline.inlinequery",
            "telegram._inline.input",
            "telegram._inline.preparedinlinemessage",
        ),
    ),
    "telegram.payments-tree": ApiCategory(
        title="Payments", module_prefixes=("telegram._payment.",)
    ),
    "telegram.games-tree": ApiCategory(title="Games", module_prefixes=("telegram._games.",)),
    "telegram.passport-tree": ApiCategory(
        title="Passport", module_prefixes=("telegram._passport.",)
    ),
    "telegram.ext.handlers-tree": ApiCategory(
        title="Handlers",
        module_prefixes=("telegram.ext._handlers.", "telegram.ext.filters"),
    ),
    "telegram.ext.persistence-tree": ApiCategory(
        title="Persistence",
        module_prefixes=(
            "telegram.ext._basepersistence",
            "telegram.ext._dictpersistence",
            "telegram.ext._picklepersistence",
        ),
    ),
    "telegram.ext.acd-tree": ApiCategory(
        title="Arbitrary Callback Data",
        module_prefixes=("telegram.ext._callbackdatacache",),
    ),
    "telegram.ext.rate-limiting-tree": ApiCategory(
        title="Rate Limiting",
        module_prefixes=("telegram.ext._aioratelimiter", "telegram.ext._baseratelimiter"),
    ),
}


def _build_api_objects() -> dict[str, str]:
    """Map every public import name to the internal module that defines its object.

    ``__all__`` is PTB's source of truth for supported imports. The defining module is retained
    only to assign each public name to the appropriate topic page without maintaining class lists.
    """
    api_objects: dict[str, str] = {}

    # Read the three supported public namespaces and ignore private version metadata.
    for api_module in API_MODULES:
        for export_name in api_module.__all__:
            if export_name.startswith("_"):
                continue

            exported_object: object = getattr(api_module, export_name)
            defining_module: str = getattr(
                exported_object, "__module__", getattr(exported_object, "__name__", "")
            )
            public_name: str = f"{api_module.__name__}.{export_name}"
            api_objects[public_name] = defining_module

    # Stable case-insensitive ordering makes every generated menu deterministic.
    ordered_items: list[tuple[str, str]] = sorted(
        api_objects.items(), key=lambda item: item[0].casefold()
    )
    return dict(ordered_items)


def _build_api_trees(api_objects: Mapping[str, str]) -> dict[str, tuple[str, ...]]:
    """Build the navigation trees from topic membership and package fallbacks.

    Topic pages claim their objects first. Everything left over is placed in Available Types,
    ``telegram.ext``, ``telegram.request``, or Auxiliary Modules, preventing duplicate entries.
    """
    api_trees: dict[str, tuple[str, ...]] = {}

    # This set prevents an object claimed by a topic page from also appearing in a fallback tree.
    categorized_objects: set[str] = set()
    telegram_category_pages: list[str] = []
    ext_category_pages: list[str] = []

    # Match public objects to topic pages through their internal module boundaries.
    for docname, category in API_CATEGORIES.items():
        category_objects: list[str] = [
            object_name
            for object_name, defining_module in api_objects.items()
            if defining_module.startswith(category.module_prefixes)
        ]
        api_trees[docname] = tuple(category_objects)
        categorized_objects.update(category_objects)

        if docname.startswith("telegram.ext."):
            ext_category_pages.append(docname)
        else:
            telegram_category_pages.append(docname)

    # These lists form the general package sections after specialized topics have been removed.
    available_types: list[str] = []  # Top-level ``telegram`` classes except Bot.
    ext_objects: list[str] = []  # Ungrouped ``telegram.ext`` exports.
    request_objects: list[str] = []  # Public request implementations.
    auxiliary_objects: list[str] = []  # Top-level modules and helper functions.

    for object_name in api_objects:
        if object_name.startswith("telegram.ext."):
            if object_name not in categorized_objects:
                ext_objects.append(object_name)
            continue

        if object_name.startswith("telegram.request."):
            request_objects.append(object_name)
            continue

        short_name: str = object_name.rpartition(".")[2]
        if short_name[:1].isupper():
            if object_name != "telegram.Bot" and object_name not in categorized_objects:
                available_types.append(object_name)
        else:
            auxiliary_objects.append(object_name)

    # Package trees contain their ordinary entries followed by generated topic pages.
    api_trees["telegram"] = ("telegram.Bot", "telegram.at-tree", *telegram_category_pages)
    api_trees["telegram.at-tree"] = tuple(available_types)
    api_trees["telegram.ext"] = (*ext_objects, *ext_category_pages)
    api_trees["telegram.request"] = tuple(request_objects)
    api_trees["telegram_auxil"] = tuple(auxiliary_objects)
    return api_trees


def _build_api_tree_dependencies() -> tuple[Path, ...]:
    """Return files whose changes must invalidate an injected navigation tree.

    The generated toctree text is not present in the physical RST file, so Sphinx cannot infer
    these dependencies itself. Tracking the extension and public ``__init__`` files fixes that.
    """
    dependencies: list[Path] = [
        Path(api_module.__file__) for api_module in API_MODULES if api_module.__file__ is not None
    ] + [Path(__file__)]
    return tuple(dependencies)


API_OBJECTS: Final[dict[str, str]] = _build_api_objects()
API_TREES: Final[dict[str, tuple[str, ...]]] = _build_api_trees(API_OBJECTS)
API_TREE_DEPENDENCIES: Final[tuple[Path, ...]] = _build_api_tree_dependencies()


def _has_marker(path: Path, marker: str) -> bool:
    """Return whether the first line marks a page as generated or maintained.

    Ownership markers let cleanup delete obsolete generated files while protecting every file that
    a maintainer may edit.
    """
    if not path.is_file():
        return False

    # Sphinx defaults to utf-8-sig, so autosummary output may begin with a byte-order mark.
    with path.open(encoding="utf-8-sig") as file:
        first_line: str = file.readline().rstrip()
    return first_line == marker


def _write_generated(path: Path, content: str) -> None:
    """Safely write one generated page without defeating Sphinx's mtime cache.

    An existing maintained page is always an error. Identical generated content is left untouched,
    so a repeated build does not make Sphinx parse the page again.
    """
    generated_content: str = f"{GENERATED_MARKER}\n\n{content.rstrip()}\n"

    # Don't overwrite manually written pages:
    if path.exists() and not _has_marker(path, GENERATED_MARKER):
        raise ExtensionError(f"Refusing to overwrite maintained documentation page: {path}")

    # Preserve the existing mtime unless the generated source actually changed.
    if not path.exists() or path.read_text(encoding="utf-8") != generated_content:
        path.write_text(generated_content, encoding="utf-8")


def _toctree(entries: Sequence[str]) -> str:
    """Render navigation text that ``source-read`` can append before RST parsing.

    Entries are lower-cased because the compatibility sources and their historic document names
    are lower-case, even though their public Python names retain normal capitalization.
    """
    lines: list[str] = [".. toctree::", "    :titlesonly:", ""]
    lines.extend(f"    {entry.lower()}" for entry in entries)
    return "\n".join(lines)


def _configure_object_targets(app: Sphinx, source_dir: Path) -> dict[str, Path]:
    """Configure autosummary's filenames and return each object's physical source path.

    Autosummary normally derives filenames from case-sensitive Python names. Explicit mappings keep
    URLs such as ``telegram.chatmember.html`` while still documenting ``telegram.ChatMember``.
    """
    object_targets: dict[str, Path] = {}
    filename_map: dict[str, str] = dict(app.config.autosummary_filename_map)

    # Both mappings use the same dotted, lower-case document name.
    for object_name in API_OBJECTS:
        filename: str = object_name.lower()
        object_targets[object_name] = source_dir / f"{filename}.rst"
        filename_map[object_name] = filename

    app.config.autosummary_filename_map = filename_map
    return object_targets


def _discover_maintained_fragments(source_dir: Path) -> dict[str, MaintainedFragment]:
    """Find maintained sources and describe the dotted wrappers they require.

    Devs work in directories such as ``telegram/ext``. Those directories are excluded from
    Sphinx discovery; generated root-level wrappers include them under the historic dotted names.
    Every discovered source must explicitly carry the False marker before it can be included.
    """
    fragments: dict[str, MaintainedFragment] = {}
    unmarked_fragments: list[Path] = []

    # Scan only the module-shaped directories owned by this extension.
    for directory in FRAGMENT_DIRECTORIES:
        directory_path: Path = source_dir / directory
        fragment_paths: list[Path] = sorted(directory_path.rglob("*.rst"))

        for fragment_path in fragment_paths:
            if not _has_marker(fragment_path, MAINTAINED_MARKER):
                unmarked_fragments.append(fragment_path)

            relative_path: Path = fragment_path.relative_to(source_dir)
            docname_parts: tuple[str, ...] = relative_path.with_suffix("").parts
            if docname_parts[-1] == "index":
                docname_parts = docname_parts[:-1]

            docname: str = ".".join(docname_parts)
            wrapper_path: Path = source_dir / f"{docname}.rst"
            fragments[docname] = MaintainedFragment(wrapper_path, relative_path)

    # Failing once with every offending path makes ownership errors straightforward to repair.
    if unmarked_fragments:
        formatted_paths: str = "\n".join(f"* {path}" for path in unmarked_fragments)
        raise ExtensionError(
            f"Maintained documentation pages need the False marker:\n{formatted_paths}"
        )

    return fragments


def _synchronize_compatibility_pages(
    source_dir: Path,
    object_targets: Mapping[str, Path],
    fragments: Mapping[str, MaintainedFragment],
) -> None:
    """Synchronize generated wrappers and topic shells before Sphinx scans the source tree.

    Wrapper pages expose nested maintained files under dotted names. Topic shells provide physical
    documents for navigation injected later. Obsolete generated pages are removed only when their
    marker proves that this extension owns them.
    """
    # Build the complete set of generated paths that are still valid in this run.
    expected_targets: set[Path] = set(object_targets.values())
    expected_targets.update(fragment.wrapper_path for fragment in fragments.values())
    expected_targets.add(source_dir / "telegram.at-tree.rst")
    expected_targets.update(source_dir / f"{docname}.rst" for docname in API_CATEGORIES)

    # Remove pages for exports or maintained fragments that no longer exist.
    for generated_path in source_dir.glob("*.rst"):
        if generated_path not in expected_targets and _has_marker(
            generated_path, GENERATED_MARKER
        ):
            generated_path.unlink()

    # Each nested maintained source receives a tiny include wrapper with its historic docname.
    for fragment in fragments.values():
        include_directive: str = f".. include:: {fragment.relative_path.as_posix()}"
        _write_generated(fragment.wrapper_path, include_directive)

    # Topic documents need only a heading; their object lists are injected during source-read.
    _write_generated(source_dir / "telegram.at-tree.rst", "Available Types\n---------------")
    for docname, category in API_CATEGORIES.items():
        label: str = docname.rpartition(".")[2]
        heading: str = "-" * len(category.title)
        page_content: str = f".. _{label}:\n\n{category.title}\n{heading}"
        _write_generated(source_dir / f"{docname}.rst", page_content)


def _generate_object_pages(
    app: Sphinx,
    source_dir: Path,
    object_targets: Mapping[str, Path],
    fragments: Mapping[str, MaintainedFragment],
) -> None:
    """Ask autosummary to create physical pages for objects without maintained overrides.

    Sphinx requires physical sources for individual class URLs. A temporary autosummary directive
    supplies the generated object list without committing that list to RST. The resulting pages
    remain in ``source_dir`` and are reused by later builds when their content is unchanged.
    """
    maintained_targets: set[Path] = {fragment.wrapper_path for fragment in fragments.values()}
    generated_objects: list[str] = []
    conflicting_targets: list[Path] = []

    # A maintained fragment replaces the default template; any other unmarked collision is unsafe.
    for object_name, target_path in object_targets.items():
        if target_path in maintained_targets:
            continue

        generated_objects.append(object_name)
        if target_path.exists() and not _has_marker(target_path, GENERATED_MARKER):
            conflicting_targets.append(target_path)

    if conflicting_targets:
        formatted_paths: str = "\n".join(f"* {path}" for path in conflicting_targets)
        raise ExtensionError(
            f"Refusing to overwrite maintained API documentation pages:\n{formatted_paths}"
        )

    # Autosummary reads this directive exactly as if it lived in a maintained RST document.
    manifest_lines: list[str] = [
        ".. autosummary::",
        "   :toctree:",
        "   :template: ptb-object.rst",
        "   :signatures: none",
        "",
    ]
    manifest_lines.extend(f"   {object_name}" for object_name in generated_objects)
    manifest_content: str = "\n".join(manifest_lines)

    # The manifest is merely input to autosummary; only its generated object pages must persist.
    with tempfile.TemporaryDirectory(prefix="ptb-api-docs-") as temporary_directory:
        manifest_path: Path = Path(temporary_directory) / "api.rst"
        manifest_path.write_text(manifest_content, encoding="utf-8")
        generate_autosummary_docs(
            [str(manifest_path)],
            output_dir=source_dir,
            app=app,
            overwrite=True,
            encoding=app.config.source_encoding,
        )


def _generate_api_pages(app: Sphinx) -> None:
    """Handle ``builder-inited`` before Sphinx discovers source documents.

    The builder and configuration are ready at this point, but the environment has not scanned the
    source directory. Creating and removing generated files here lets normal Sphinx discovery and
    incremental-build logic handle them like ordinary RST sources.
    """
    source_dir: Path = Path(app.srcdir)

    # Resolve every source path first, then synchronize wrappers and ordinary object pages.
    object_targets: dict[str, Path] = _configure_object_targets(app, source_dir)
    fragments: dict[str, MaintainedFragment] = _discover_maintained_fragments(source_dir)
    _synchronize_compatibility_pages(source_dir, object_targets, fragments)
    _generate_object_pages(app, source_dir, object_targets, fragments)


def _inject_api_tree(app: Sphinx, docname: str, source: list[str]) -> None:
    """Handle ``source-read`` by appending generated navigation before RST parsing.

    Sphinx passes source text in a one-item list so event handlers can replace it. The injected
    tree remains absent from disk, while explicit dependencies ensure export changes invalidate
    the page.
    """
    entries: tuple[str, ...] | None = API_TREES.get(docname)
    if not entries:
        return

    # Physical RST mtimes cannot represent changes to text generated from Python exports.
    for dependency in API_TREE_DEPENDENCIES:
        app.env.note_dependency(dependency)

    # Replacing the list item changes the text Sphinx will parse without modifying the source file.
    source[0] = f"{source[0].rstrip()}\n\n{_toctree(entries)}\n"


def setup(app: Sphinx) -> ExtensionMetadata:
    """Register page generation before discovery and tree injection before source parsing."""
    # Priority 400 runs before autosummary's builder-inited handler at the default priority 500.
    app.connect("builder-inited", _generate_api_pages, priority=400)
    app.connect("source-read", _inject_api_tree)
    return {
        "version": "1.0",
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }
