#
#  A library that provides a Python interface to the Telegram Bot API
#  Copyright (C) 2015-2026
#  Leandro Toledo de Souza <devs@python-telegram-bot.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Lesser Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser Public License for more details.
#
#  You should have received a copy of the GNU Lesser Public License
#  along with this program.  If not, see [http://www.gnu.org/licenses/].
"""Generate the public API reference from PTB's ``__all__`` exports.

Sphinx's autosummary extension can generate one source document per object, but it normally expects
the object list to be maintained in an RST file. This extension builds that list from PTB's public
exports instead and removes the generated sources when the build finishes.

Relevant Sphinx documentation:

* Autosummary: https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html
* Custom templates: https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html#customizing-templates
* Sphinx events: https://www.sphinx-doc.org/en/master/extdev/event_callbacks.html
"""

from __future__ import annotations

import tempfile
from collections import Counter
from importlib import import_module
from pathlib import Path
from types import ModuleType
from typing import TYPE_CHECKING, Final

from sphinx.errors import ExtensionError
from sphinx.ext.autosummary.generate import generate_autosummary_docs
from sphinx.util import logging

if TYPE_CHECKING:
    from collections.abc import Iterable, Sequence

    from sphinx.application import Sphinx


LOGGER = logging.getLogger(__name__)

API_MODULES: Final = ("telegram", "telegram.ext", "telegram.request")
GENERATED_MARKER: Final = (
    ".. This file is generated by docs.auxil.api_docs. Do not edit it directly."
)
MANUAL_MARKER: Final = (
    ".. This API page is maintained manually and is not generated by docs.auxil.api_docs."
)

# Most API objects belong in the package's default, alphabetically sorted toctree. Objects listed
# in these hand-written topic trees are subtracted from that default tree to avoid duplicate
# navigation entries.
TOP_LEVEL_SPECIALIZED_TREES: Final = (
    "telegram.inline-tree",
    "telegram.payments-tree",
    "telegram.games-tree",
    "telegram.passport-tree",
    "telegram.stickers-tree",
)
EXT_SPECIALIZED_TREES: Final = (
    "telegram.ext.handlers-tree",
    "telegram.ext.persistence-tree",
    "telegram.ext.acd-tree",
    "telegram.ext.rate-limiting-tree",
)

# These markers keep the small package-level RST files readable. During ``source-read`` they are
# replaced in memory with toctrees built from the current public exports.
TOCTREE_MARKERS: Final = {
    "telegram.at-tree": ".. ptb-api-toctree:: available-types",
    "telegram.ext": ".. ptb-api-toctree:: ext",
    "telegram.request": ".. ptb-api-toctree:: request",
}

# The old per-object RST files were almost all identical. Only genuine rendering differences live
# here; everything else receives the default options from the autosummary template.
DEFAULT_AUTODOC_OPTION_BLOCK: Final = "    :members:\n    :show-inheritance:"
AUTODOC_OPTION_BLOCKS: Final = {
    "telegram.Chat": (
        "    :members:\n    :show-inheritance:\n    :inherited-members: TelegramObject, object"
    ),
    "telegram.ChatFullInfo": (
        "    :members:\n    :show-inheritance:\n    :inherited-members: TelegramObject, object"
    ),
    "telegram.ext.ApplicationBuilder": "    :members:",
    "telegram.ext.CallbackContext": "    :members:",
    "telegram.ext.ExtBot": (
        "    :show-inheritance:\n"
        "    :members: insert_callback_data, defaults, rate_limiter, initialize, shutdown, "
        "callback_data_cache"
    ),
    "telegram.ext.PersistenceInput": "    :show-inheritance:",
}


def _api_object_names() -> tuple[str, ...]:
    """Return the public API objects that should have their own documentation page.

    ``__all__`` is already PTB's source of truth for the supported public API. Reusing it here
    means exporting a new class is enough to give it a reference page.
    """
    names = []
    for module_name in API_MODULES:
        module = import_module(module_name)
        for name in module.__all__:
            obj = getattr(module, name)
            if not name.startswith("_") and not isinstance(obj, ModuleType):
                names.append(f"{module_name}.{name}")

    return tuple(sorted(names, key=str.casefold))


def _docname(object_name: str) -> str:
    """Return the historic, lower-case Sphinx document name for an API object.

    ``autosummary_filename_map`` supports this explicit mapping:
    https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html#confval-autosummary_filename_map

    Keeping the old names preserves URLs such as ``telegram.chatmember.html``.
    """
    return object_name.lower()


def _generated_path(source_dir: Path, object_name: str) -> Path:
    return source_dir / f"{_docname(object_name)}.rst"


def _has_marker(path: Path, marker: str) -> bool:
    if not path.is_file():
        return False

    # Sphinx's default source encoding is ``utf-8-sig``, so autosummary output carries a BOM.
    with path.open(encoding="utf-8-sig") as file:
        return file.readline().rstrip() == marker


def _is_generated(path: Path) -> bool:
    return _has_marker(path, GENERATED_MARKER)


def _is_manual(path: Path) -> bool:
    """Return whether *path* is an explicit hand-written override of a generated API page."""
    return _has_marker(path, MANUAL_MARKER)


def _remove_generated_pages(source_dir: Path) -> None:
    """Remove only API pages carrying our generator marker.

    The marker check protects package pages, topic trees, and manual object-page overrides.
    """
    for path in source_dir.glob("telegram.*.rst"):
        if _is_generated(path):
            path.unlink()


def _autosummary_manifest(object_names: Sequence[str]) -> str:
    objects = "\n".join(f"   {name}" for name in object_names)
    return (
        ".. autosummary::\n"
        "   :toctree:\n"
        "   :template: ptb-object.rst\n"
        "   :signatures: none\n"
        f"\n{objects}\n"
    )


def _configure_autosummary(app: Sphinx, object_names: Sequence[str]) -> None:
    filename_map = dict(app.config.autosummary_filename_map)
    filename_map.update({name: _docname(name) for name in object_names})
    app.config.autosummary_filename_map = filename_map

    context = dict(app.config.autosummary_context)
    context.update(
        {
            "ptb_autodoc_option_blocks": AUTODOC_OPTION_BLOCKS,
            "ptb_default_autodoc_option_block": DEFAULT_AUTODOC_OPTION_BLOCK,
        }
    )
    app.config.autosummary_context = context


def _generate_api_pages(app: Sphinx) -> None:
    """Create transient autosummary sources before Sphinx scans for documents.

    Autosummary still produces physical RST sources because Sphinx discovers documents by source
    path. They are ignored by Git and deleted on both successful and failed builds, so they never
    become files that maintainers need to review or update.
    """
    source_dir = Path(app.srcdir)
    # Clean up a previous build that was interrupted before ``build-finished`` could run.
    _remove_generated_pages(source_dir)

    object_names = _api_object_names()
    object_paths = {name: _generated_path(source_dir, name) for name in object_names}
    manual_names = [name for name, path in object_paths.items() if _is_manual(path)]
    generated_names = [name for name in object_names if name not in manual_names]
    generated_paths = [object_paths[name] for name in generated_names]

    # A hand-written page must opt in with ``MANUAL_MARKER``. This prevents an untracked or stale
    # file from silently taking precedence over the generated public API documentation.
    conflicts = [path for path in object_paths.values() if path.exists() and not _is_manual(path)]
    if conflicts:
        formatted = "\n".join(f"* {path}" for path in conflicts)
        raise ExtensionError(
            "Refusing to overwrite API documentation pages without the manual-page marker:\n"
            f"{formatted}"
        )

    _configure_autosummary(app, object_names)

    try:
        with tempfile.TemporaryDirectory(prefix="ptb-api-docs-") as temp_dir:
            manifest = Path(temp_dir) / "api.rst"
            manifest.write_text(_autosummary_manifest(generated_names), encoding="utf-8")
            generate_autosummary_docs(
                [str(manifest)],
                output_dir=source_dir,
                app=app,
                overwrite=True,
                encoding=app.config.source_encoding,
            )
    except Exception:
        _remove_generated_pages(source_dir)
        raise

    missing = [path for path in generated_paths if not _is_generated(path)]
    if missing:
        formatted = "\n".join(f"* {path}" for path in missing)
        _remove_generated_pages(source_dir)
        raise ExtensionError(f"Autosummary did not generate the expected API pages:\n{formatted}")

    LOGGER.info(
        "generated %d transient API documentation pages; using %d manual overrides",
        len(generated_paths),
        len(manual_names),
    )


def _toctree_entries(path: Path) -> list[str]:
    entries = []
    in_toctree = False

    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith(".. toctree::"):
            in_toctree = True
            continue
        if not in_toctree:
            continue
        if not line.strip() or line.startswith("    :"):
            continue
        if line.startswith("    "):
            entries.append(line.strip().removesuffix(".rst"))
            continue
        in_toctree = False

    return entries


def _specialized_entries(source_dir: Path, tree_docnames: Iterable[str]) -> list[str]:
    entries = []
    for docname in tree_docnames:
        entries.extend(_toctree_entries(source_dir / f"{docname}.rst"))

    duplicates = sorted(name for name, count in Counter(entries).items() if count > 1)
    if duplicates:
        formatted = ", ".join(duplicates)
        raise ExtensionError(
            f"API objects occur in more than one specialized toctree: {formatted}"
        )

    return entries


def _render_toctree(entries: Iterable[str]) -> str:
    body = "\n".join(f"    {entry}" for entry in entries)
    return f".. toctree::\n    :titlesonly:\n\n{body}"


def _api_toctrees(source_dir: Path) -> dict[str, str]:
    """Build the default package toctrees while preserving hand-curated topic groupings."""
    object_docnames = {_docname(name) for name in _api_object_names()}

    top_level = {name for name in object_docnames if name.count(".") == 1}
    top_specialized = _specialized_entries(source_dir, TOP_LEVEL_SPECIALIZED_TREES)
    unknown_top = set(top_specialized).difference(top_level)
    if unknown_top:
        formatted = ", ".join(sorted(unknown_top))
        raise ExtensionError(f"Unknown objects in specialized telegram toctrees: {formatted}")

    available_types = top_level.difference(top_specialized, {"telegram.bot"})

    ext = {name for name in object_docnames if name.startswith("telegram.ext.")}
    ext_specialized = _specialized_entries(source_dir, EXT_SPECIALIZED_TREES)
    allowed_manual_ext_pages = {"telegram.ext.filters"}
    unknown_ext = set(ext_specialized).difference(ext, allowed_manual_ext_pages)
    if unknown_ext:
        formatted = ", ".join(sorted(unknown_ext))
        raise ExtensionError(f"Unknown objects in specialized telegram.ext toctrees: {formatted}")

    ext_package = ext.difference(ext_specialized)
    request = {name for name in object_docnames if name.startswith("telegram.request.")}

    return {
        "telegram.at-tree": _render_toctree(sorted(available_types)),
        "telegram.ext": _render_toctree([*sorted(ext_package), *EXT_SPECIALIZED_TREES]),
        "telegram.request": _render_toctree(sorted(request)),
    }


def _inject_api_toctree(app: Sphinx, docname: str, source: list[str]) -> None:
    """Replace a package-page marker with its generated toctree in memory."""
    marker = TOCTREE_MARKERS.get(docname)
    if marker is None:
        return
    if source[0].count(marker) != 1:
        raise ExtensionError(f"{docname}.rst must contain exactly one {marker!r} marker")

    source[0] = source[0].replace(marker, _api_toctrees(Path(app.srcdir))[docname])


def _cleanup_api_pages(app: Sphinx, exception: Exception | None) -> None:
    """Remove transient sources even when Sphinx reports a build exception."""
    _remove_generated_pages(Path(app.srcdir))


def setup(app: Sphinx) -> dict[str, object]:
    app.connect("builder-inited", _generate_api_pages, priority=400)
    app.connect("source-read", _inject_api_toctree)
    app.connect("build-finished", _cleanup_api_pages)
    return {
        "version": "1.0",
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }
