flowchart TB
  subgraph legend[Legend]
    direction TB
      entryPointLegend(("/start")):::entryPoint --> terminationLegend(("End")):::termination
      userInput(User Input):::userInput --> |"Bot reply"| state((State)):::state
  end
  classDef userInput  fill:#2a5279, color:#ffffff, stroke:#ffffff
  classDef state fill:#222222, color:#ffffff, stroke:#ffffff
  classDef entryPoint fill:#009c11, stroke:#42FF57, color:#ffffff
  classDef termination fill:#bb0007, stroke:#E60109, color:#ffffff
  style legend fill:#999999, stroke-width:2px, stroke:#333333
