name: Create Chango Fragment
on:
  pull_request:
    types:
      - opened
      - reopened

permissions: {}

jobs:
  create-chango-fragment:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    name: create-chango-fragment
    runs-on: ubuntu-latest
    steps:

      # Create the new fragment
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: Bibo-Joshi/chango@969684469005dd2e03451f15bfd810f2338bf072 # v0.3.2
        with:
          github-token: ${{ secrets.CHANGO_PAT }}
          query-issue-types: true


