name: Unit Tests
on:
  pull_request:
    types: [synchronize, reopened, ready_for_review]
    paths:
      - src/telegram/**
      - tests/**
      - .github/workflows/unit_tests.yml
      - pyproject.toml
  push:
    branches:
      - master

permissions: {}

jobs:
  pytest:
    name: pytest
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14', '3.15.0-beta.2']
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - python-version: '3.14t'
            os: ubuntu-latest
      fail-fast: False
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -W ignore -m pip install --upgrade pip
          python -W ignore -m pip install . --group tests

      - name: Test with pytest
        # We run 4 different suites here
        # 1. Test just utils.datetime.py without pytz being installed
        # 2. Test just test_no_passport.py without passport dependencies being installed
        # 3. Test just test_rate_limiter.py without passport dependencies being installed
        # 4. Test everything else
        # The first & second one are achieved by mocking the corresponding import
        # See test_helpers.py & test_no_passport.py for details
        run: |
          # Mask bot tokens and payment provider tokens in the logs.
          # Needs to be run before pytest so Github knows about them
          python -c '
          import base64
          import json
          import os

          def mask(value):
              if not value:
                  return
              print(f"::add-mask::{value}")

          bots = os.environ.get("BOTS")
          mask(bots)
          if bots:
              for bot in json.loads(base64.b64decode(bots).decode("utf-8")):
                  for key in ("token", "payment_provider_token"):
                      mask(bot.get(key))
          '

          # We test without optional dependencies first. This includes:
          # - without pytz
          # - without jobqueue
          # - without ratelimiter
          # - without webhooks
          # - without arbitrary callback data
          # - without socks support
          # - without http2 support
          TO_TEST="test_no_passport.py or test_datetime.py or test_defaults.py or test_jobqueue.py or test_applicationbuilder.py or test_ratelimiter.py or test_updater.py or test_callbackdatacache.py or test_request.py"
          pytest -v --cov -k "${TO_TEST}" --junit-xml=.test_report_no_optionals_junit.xml
          opt_dep_status=$?
          
          # Test the rest
          export TEST_WITH_OPT_DEPS='true'
          pip install .[all]
          # `-n auto --dist worksteal` uses pytest-xdist to run tests on multiple CPU
          # workers. Increasing number of workers has little effect on test duration, but it seems
          # to increase flakyness.
          pytest -v --cov --cov-append -n auto --dist worksteal --junit-xml=.test_report_optionals_junit.xml
          main_status=$?
          # exit with non-zero status if any of the two pytest runs failed
          exit $(( ${opt_dep_status} || ${main_status} ))
        env:
          JOB_INDEX: ${{ strategy.job-index }}
          BOTS: ${{ secrets.BOTS }} 
          TEST_WITH_OPT_DEPS : "false"
          TEST_BUILD: "true"
        shell: bash --noprofile --norc {0}

      - name: Test Summary
        id: test_summary
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2.4
        if: always()  # always run, even if tests fail
        with:
          paths: |
            .test_report_no_optionals_junit.xml
            .test_report_optionals_junit.xml

      - name: Submit coverage
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7.0.0
        with:
          env_vars: OS,PYTHON
          name: ${{ matrix.os }}-${{ matrix.python-version }}
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7.0.0
        if: ${{ !cancelled() }}
        with:
          files: .test_report_no_optionals_junit.xml,.test_report_optionals_junit.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
